import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'limonada-coco',
    name: 'Limonada de Coco Ice',
    price: 19000,
    category: 'Dulces',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDXafMEd8-8kTDBpAw2y8KfXeiTR4ZukUCsaOB16WCrOCNQ9AQiMaTaxK6hLRmdcnqzfhTuyxPDgOKn5SRw4DZU83ZNdV41KSikPpMWwBBMtIs0hmekUr4MwXoc4-Pe-fECMnJnjq7z5pA0Qj1n5K4GdevTFvfO7Qs7wYGRxqZlSlpT12pogKlCSlrx3JlIqazLVoDeO9dLJKo7dT37PoRXAt2MbjHZojLBuUFSDdEz-ZkMcucIkO7s1qlEYN9Ah88BWvZcUQI9GwKt',
    description: 'Deliciosa combinación cremosa de coco natural con un toque de limón ácido bajo cero.',
  },
  {
    id: 'frutos-rojos',
    name: 'Frutos Rojos Escarchados',
    price: 20000,
    category: 'Dulces',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCa2h5WUo0BnY4b6ggna35X4KzwgpQWHsoZc29V0chX9sbUl0Zs_ZrzDNRaikyRH3jcBwogKbae3ozj4v_YYpSOtV7lsu-BljSVjQqoh4h9CLx1o8-77ouha7Ubul2kCvlXgY-BzcUbh7yxOWnkg9pGn_DtVSvseqxUQUvzEwDEclv2GdKNMP9pdlFBXRgxonJludc0cbWIuMPqUKksLo1jPbSW-13ZC7afNaOqbGBUhqQwlA1yct8y-vdzqnBKf6naaquL1kpBPZiS',
    description: 'Intenso granizado de fresas fresquitas y frambuesas silvestres escarchadas en su punto.',
  },
  {
    id: 'maracuya-neon',
    name: 'Maracuyá Neón',
    price: 18000,
    category: 'Cítricos',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBU0M2QqIP3w30XBeLWE-h8cJWBJDSuOkr_5LmQOQ2LduzdRYF0FhTqnDmDIDggDg0ySlqerdue4s7unpRp1aFYpqTKg6hdFIYR0d3b8Kl_8H0_pWELuTAgn_-P4a_on8jMECbJNSBJasnjuB80QEcYzJxm0BMQqAIu8mYduoN8qvgBRDQylp_z7l1QK_aaFgGD42OU_Rj5VrzvvpKPtGmkWMX-gO9kYOixQV5p929BFZ-YrCkcnX57KMFudrxlyBF2rfDBo5A2FBk7',
    description: 'Refrescante pulpa de maracuyá pura de sabor cítrico vibrante con un fascinante tono neón natural.',
  },
  {
    id: 'mora-azul',
    name: 'Mora Azul Extrema',
    price: 22000,
    category: 'Dulces',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA4FvBknqcgIagK5naCbKz4dgVNvdixoWPNpfSSALEeyIdf2eQ00fbdTkWe2nzu9miflkhPOoeCyyVi-YzuK3d0SmESz01ZV5IKCSjA5Zr77bjE-JyoVcRu2vEotZuNM5L94Xbtc8n5lkrT6xuWqTX0LU2MyASHDZ3glY-ejd3rWQNiNZ68-_dKr6p79e0VX8j4MJ1w0a3kxNQAj4BkkoIqcG6qv3rFxetp1vogYw0jx3Dr72OsJSxA7lInAKLJNlFLqD7q2wywlj7T',
    description: 'Granizado extremo de moras azules con una textura cristalina celestial de la cordillera polar.',
  },
  {
    id: 'manzana-verde',
    name: 'Manzana Verde Ácida',
    price: 18000,
    category: 'Cítricos',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&q=80&w=600',
    description: 'Puro shock de manzana verde crocante y ácida que activará todos tus sentidos y refrescará tu día.',
  },
  {
    id: 'cereza-citrica',
    name: 'Cereza Cítrica',
    price: 19000,
    category: 'Cítricos',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDmyUrmqYlbgiA-rEcReWu-X72f8I_WIAkIFcGZMS7P8GupA8t4I6I4meCkWc_vOHIlwoUqSPTiHZchYxQGLsHJvwxYgwcAA9GPm8QsijYO2rF25nMSK6Ca4OjzRRWSL8HTBszQaMmJ3ObKri3x-HpUSpVKH2bDCfUX_qFJ7ytAQRNlpkreSyldm6dOjhW7FC52PzOuKV04Vx0HsIlEknQBT9fYFrrhlBQ1q6c55j0D1gt6azPSGZL3RBCM9vBTMXTJigCvTn1uRsBo',
    description: 'Cerezas rojas seleccionadas y trituradas bajo cero con el balance perfecto de jugo de limón real.',
  },
  {
    id: 'mango-biche',
    name: 'Mango Biche con Sal y Limón',
    price: 22000,
    category: 'Cítricos',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBU0EIAiYA24_kF2GNusiMLkVW3auR2xBYDeG5F7WUnXh0ydz635mHcQAGZ_RfXSpSYWH18iZusbvv0Di42RHK-nByIEif4O_BKwM0ZADRMInjSZU023NvhQuU8E09DYH3lk0tPkBFM9dwZnFMm9Ixm2arSoraz4nM4BV7OGXixr2EntHXnYgaJaBsZ-uTQFP-O-5JC6MpdPNHrb2JOZa_x3tu4jwjPOgR8Ei3VgizG9URXikeSWJd-EYPIAPWqkCiWNu4RzQblUgD9',
    description: 'El clásico inolvidable: mango biche recién cosechado rascado con sal marina cristalizada y limón.',
  },
  {
    id: 'mix-sebas',
    name: 'Mix Sebas (3 Sabores)',
    price: 30000,
    category: 'Dulces',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAxyrujr9y9Su02T6ZVO1_rfCwuE-wchKvadHOG3T33ci1uyvltGqqbB0fWgg11MzHUnws-6j5kyb-bDMP5xJsuKB2ad9O2Kfwc1p3JkXcIvLp2DWk3fB2OXcL4b3k9EL_rynieR8CnxcfbPVwITsFj-HLOZCR8Hd3_k70u4KMu_GDxMzAJezxs4LQF61f8l4E0CCrZdDccl-R0zKSsXYvpQoaLchQi7C7B-R_pAzgO_6_quX70HwxDGDxC1BQ05d6Annd1w56iNigU',
    description: 'Nuestra combinación estelar: capas perfectas de sabor azul, rojo y amarillo que se funden de manera genial.',
    tag: 'Best Value',
  },
];
